apiVersion: v1
kind: Service
metadata:
  name: telemetry-service
  namespace: telemetry-namespace
spec:
  type: NodePort
  selector:
    app: telemetry-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
